title: eXtant Wiki
description: A wiki for all the projects in eXtant
theme: just-the-docs

url: https://extant-cmg.github.io/eXtant-wiki

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/eXtant-CMG/eXtant-wiki
