title: eXtant Documentation
description: A wiki for all the projects in eXtant
theme: just-the-docs

url: https://extant-cmg.github.io/eXtant-wiki

aux_links: # remove if you don't want this link to appear on your pages
  Template Repository: https://github.com/eXtant-CMG/eXtant-wiki

collections:
  axolotl:
    permalink: "/:collection/:path/"
    output: true
  loxensis:
    permalink: "/:collection/:path/"
    output: true
  bibundina:
    permalink: "/:collection/:path/"
    output: true
  diff-annotator:
    permalink: "/:collection/:path/"
    output: true

just_the_docs:
  collections:
    axolotl:
      name: Axolotl
    loxensis:
      name: Keystroke Loxensis
    bibundina:
      name: Bibundina
    diff-annotator:
      name: Diff-Annotator

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: purple
  warning:
    title: Important
    color: red
  example:
    title: Example
    color: grey-lt

color_scheme: dark

